import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import NavBar from "@/components/NavBar";
import AuthLoader from "@/components/AuthLoader";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/Footer";
import { ThemeProvider } from "next-themes";

const vazirFont = localFont({
  src: "../../public/fonts/Vazir.woff2",
  variable: "--font-vazir",
});

export const metadata: Metadata = {
  title: "English Learning app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir={"rtl"}
      className={`${vazirFont.variable}`}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ReduxProvider>
            <AuthLoader>
              <NavBar />
              {children}
              <Footer />
            </AuthLoader>
          </ReduxProvider>
          <ToastContainer position="top-right" autoClose={3000} rtl={true} />
        </ThemeProvider>
      </body>
    </html>
  );
}
