# Generated by Django 6.0.5 on 2026-06-01 14:29

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_review_student_enrollment_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseId',
            field=models.CharField(default=courses.models.Course.generate_course_id, max_length=20, unique=True),
        ),
    ]
